#!/usr/bin/env perl
# check if device contains Pegasus Spyware files reported in https://info.lookout.com/rs/051-ESQ-475/images/lookout-pegasus-technical-analysis.pdf
 
use warnings;
use strict;

my @files = qw< /--early-boot /var/root/test.app /private/var/tmp/crw /private/var/tmp/cr /private/var/tmp/st_data >;
my @found = ();

for( @files ){
    push @found, $_ if -f;
}

if(@found){
    print "\n!!Your device might be infected!!\n\nFound files:\n";
    print join "\n", @found;
} else { print "\nOK: no Pegasus spyware found\n\n" }
print "\n\n";
